"""Toy Story Racer challenge metadata.

Source: TSR Compendio.docx supplied for this project.
Contains all 200 challenge locations.
"""

CHALLENGES = [
    {
        "character": 'Woody',
        "number": 1,
        "name": 'Shootout at the attic corral',
        "type": 'Knockout race',
        "required_soldiers": 0,
        "unlocks": None,
    },
    {
        "character": 'Woody',
        "number": 2,
        "name": 'Buzzing arcade machines',
        "type": 'Smash challenge',
        "required_soldiers": 1,
        "unlocks": None,
    },
    {
        "character": 'Woody',
        "number": 3,
        "name": 'Western trophy',
        "type": 'Race tournament challenge',
        "required_soldiers": 3,
        "unlocks": None,
    },
    {
        "character": 'Woody',
        "number": 4,
        "name": 'Something in the attic!',
        "type": 'Survival race challenge',
        "required_soldiers": 9,
        "unlocks": None,
    },
    {
        "character": 'Woody',
        "number": 5,
        "name": 'Show them who is boss',
        "type": 'Smash tag challenge',
        "required_soldiers": 10,
        "unlocks": None,
    },
    {
        "character": 'Woody',
        "number": 6,
        "name": 'Sheriff on skates?',
        "type": 'Race challenge',
        "required_soldiers": 15,
        "unlocks": None,
    },
    {
        "character": 'Woody',
        "number": 7,
        "name": 'Speedy sheriff',
        "type": 'Lap trial challenge',
        "required_soldiers": 21,
        "unlocks": None,
    },
    {
        "character": 'Woody',
        "number": 8,
        "name": 'Sheriff arcade roundup',
        "type": 'Collection challenge',
        "required_soldiers": 24,
        "unlocks": None,
    },
    {
        "character": 'Woody',
        "number": 9,
        "name": 'Seaside sheriff',
        "type": 'Endurance challenge',
        "required_soldiers": 25,
        "unlocks": None,
    },
    {
        "character": 'Woody',
        "number": 10,
        "name": 'Trial by the sea',
        "type": 'Lap trial challenge (reverse)',
        "required_soldiers": 30,
        "unlocks": None,
    },
    {
        "character": 'Woody',
        "number": 11,
        "name": 'Shopping sheriff',
        "type": 'Tag challenge',
        "required_soldiers": 45,
        "unlocks": 'Hamm',
    },
    {
        "character": 'Woody',
        "number": 12,
        "name": 'Not shopping speed backwards?',
        "type": 'Target challenge',
        "required_soldiers": 50,
        "unlocks": None,
    },
    {
        "character": 'Woody',
        "number": 13,
        "name": 'Rounding up the neighbors',
        "type": 'Collection challenge',
        "required_soldiers": 55,
        "unlocks": None,
    },
    {
        "character": 'Woody',
        "number": 14,
        "name": "Andy's super speed off",
        "type": 'Survival race challenge',
        "required_soldiers": 60,
        "unlocks": None,
    },
    {
        "character": 'Woody',
        "number": 15,
        "name": 'Wild wild Woody',
        "type": 'Smash tournament challenge',
        "required_soldiers": 75,
        "unlocks": None,
    },
    {
        "character": 'Woody',
        "number": 16,
        "name": 'Knockout pizzeria Woody!',
        "type": 'Knockout race challenge (reverse)',
        "required_soldiers": 75,
        "unlocks": None,
    },
    {
        "character": 'Woody',
        "number": 17,
        "name": 'Skate tags',
        "type": 'Tag challenge',
        "required_soldiers": 95,
        "unlocks": 'Mr. Potato Head',
    },
    {
        "character": 'Woody',
        "number": 18,
        "name": 'Backward neighborhood?',
        "type": 'Race challenge (reverse)',
        "required_soldiers": 103,
        "unlocks": None,
    },
    {
        "character": 'Woody',
        "number": 19,
        "name": 'Knockout trophy',
        "type": 'Knockout race tournament challenge',
        "required_soldiers": 105,
        "unlocks": None,
    },
    {
        "character": 'Woody',
        "number": 20,
        "name": 'Sweetheart survivor?',
        "type": 'Super survival race challenge',
        "required_soldiers": 190,
        "unlocks": None,
    },
    {
        "character": 'Buzz',
        "number": 1,
        "name": 'Space race trophy',
        "type": 'Race tournament challenge',
        "required_soldiers": 0,
        "unlocks": None,
    },
    {
        "character": 'Buzz',
        "number": 2,
        "name": 'To infinity and beyond!',
        "type": 'Race challenge',
        "required_soldiers": 1,
        "unlocks": None,
    },
    {
        "character": 'Buzz',
        "number": 3,
        "name": "Knock 'em out spaceranger",
        "type": 'Knockout race challenge',
        "required_soldiers": 3,
        "unlocks": None,
    },
    {
        "character": 'Buzz',
        "number": 4,
        "name": 'Get a move on spaceranger',
        "type": 'Lap trial challenge',
        "required_soldiers": 9,
        "unlocks": None,
    },
    {
        "character": 'Buzz',
        "number": 5,
        "name": 'There can be only one',
        "type": 'Smash challenge',
        "required_soldiers": 10,
        "unlocks": None,
    },
    {
        "character": 'Buzz',
        "number": 6,
        "name": 'Collect them all Buzz',
        "type": 'Collection challenge',
        "required_soldiers": 15,
        "unlocks": None,
    },
    {
        "character": 'Buzz',
        "number": 7,
        "name": 'Prehistoric yard adventures',
        "type": 'Survival race challenge',
        "required_soldiers": 20,
        "unlocks": 'Rex',
    },
    {
        "character": 'Buzz',
        "number": 8,
        "name": 'Endure this spaceranger',
        "type": 'Endurance challenge',
        "required_soldiers": 22,
        "unlocks": None,
    },
    {
        "character": 'Buzz',
        "number": 9,
        "name": 'You need speed to catch these',
        "type": 'Tag challenge',
        "required_soldiers": 22,
        "unlocks": None,
    },
    {
        "character": 'Buzz',
        "number": 10,
        "name": 'Hurricane seaside survivor',
        "type": 'Survival race challenge',
        "required_soldiers": 26,
        "unlocks": None,
    },
    {
        "character": 'Buzz',
        "number": 11,
        "name": 'Battling with style',
        "type": 'Smash tournament challenge',
        "required_soldiers": 30,
        "unlocks": None,
    },
    {
        "character": 'Buzz',
        "number": 12,
        "name": 'Too slow and its K.O. ranger',
        "type": 'Knockout race challenge (reverse)',
        "required_soldiers": 45,
        "unlocks": None,
    },
    {
        "character": 'Buzz',
        "number": 13,
        "name": "Buzz's attic rally attack?",
        "type": 'Target challenge',
        "required_soldiers": 52,
        "unlocks": None,
    },
    {
        "character": 'Buzz',
        "number": 14,
        "name": 'Weapon training spaceranger',
        "type": 'Smash tag challenge',
        "required_soldiers": 53,
        "unlocks": None,
    },
    {
        "character": 'Buzz',
        "number": 15,
        "name": 'Warp speed is needed spaceranger',
        "type": 'Lap trial challenge (reverse)',
        "required_soldiers": 58,
        "unlocks": None,
    },
    {
        "character": 'Buzz',
        "number": 16,
        "name": 'Keep going if you can ranger',
        "type": 'Knockout race tournament challenge',
        "required_soldiers": 75,
        "unlocks": None,
    },
    {
        "character": 'Buzz',
        "number": 17,
        "name": "Gotta catch 'em up spaceranger",
        "type": 'Collection challenge',
        "required_soldiers": 75,
        "unlocks": None,
    },
    {
        "character": 'Buzz',
        "number": 18,
        "name": 'Get your skates on spaceranger',
        "type": 'Smash tag challenge',
        "required_soldiers": 103,
        "unlocks": 'Little Green Man',
    },
    {
        "character": 'Buzz',
        "number": 19,
        "name": 'Shop till you drop Buzz',
        "type": 'Super survival race challenge (reverse)',
        "required_soldiers": 109,
        "unlocks": None,
    },
    {
        "character": 'Buzz',
        "number": 20,
        "name": 'Go go K.O. ranger!',
        "type": 'Smash tournament challenge',
        "required_soldiers": 120,
        "unlocks": None,
    },
    {
        "character": 'Buzz',
        "number": 21,
        "name": "It's your race ranger",
        "type": 'Race tournament challenge',
        "required_soldiers": 150,
        "unlocks": None,
    },
    {
        "character": 'Buzz',
        "number": 22,
        "name": 'Knock door ginger',
        "type": 'Countdown race challenge',
        "required_soldiers": 190,
        "unlocks": None,
    },
    {
        "character": 'RC',
        "number": 1,
        "name": 'Radio controlled trophy',
        "type": 'Smash tournament challenge',
        "required_soldiers": 0,
        "unlocks": None,
    },
    {
        "character": 'RC',
        "number": 2,
        "name": 'Neighborhood watch!',
        "type": 'Race challenge',
        "required_soldiers": 1,
        "unlocks": None,
    },
    {
        "character": 'RC',
        "number": 3,
        "name": 'On your marks, get set, snow!',
        "type": 'Race challenge',
        "required_soldiers": 3,
        "unlocks": None,
    },
    {
        "character": 'RC',
        "number": 4,
        "name": 'Snow go!',
        "type": 'Race challenge (reverse)',
        "required_soldiers": 9,
        "unlocks": None,
    },
    {
        "character": 'RC',
        "number": 5,
        "name": 'Shopaholic!',
        "type": 'Race challenge',
        "required_soldiers": 10,
        "unlocks": None,
    },
    {
        "character": 'RC',
        "number": 6,
        "name": 'Pizza for Mr R.C. car',
        "type": 'Collection challenge',
        "required_soldiers": 15,
        "unlocks": None,
    },
    {
        "character": 'RC',
        "number": 7,
        "name": 'Closing time at the mall',
        "type": 'Lap trial challenge',
        "required_soldiers": 22,
        "unlocks": None,
    },
    {
        "character": 'RC',
        "number": 8,
        "name": 'Clearing out the attic',
        "type": 'Knockout race challenge',
        "required_soldiers": 25,
        "unlocks": None,
    },
    {
        "character": 'RC',
        "number": 9,
        "name": 'Everybody needs good neighbors',
        "type": 'Survival race challenge',
        "required_soldiers": 27,
        "unlocks": None,
    },
    {
        "character": 'RC',
        "number": 10,
        "name": 'Dinner time!',
        "type": 'Endurance challenge (reverse)',
        "required_soldiers": 30,
        "unlocks": None,
    },
    {
        "character": 'RC',
        "number": 11,
        "name": 'Trouble at the pier',
        "type": 'Knockout race challenge (reverse)',
        "required_soldiers": 45,
        "unlocks": None,
    },
    {
        "character": 'RC',
        "number": 12,
        "name": 'Super super go wow racer!',
        "type": 'Race tournament challenge',
        "required_soldiers": 50,
        "unlocks": None,
    },
    {
        "character": 'RC',
        "number": 13,
        "name": 'Yard sale clearance',
        "type": 'Endurance challenge',
        "required_soldiers": 56,
        "unlocks": None,
    },
    {
        "character": 'RC',
        "number": 14,
        "name": 'Mind the mud!',
        "type": 'Lap trial challenge (reverse)',
        "required_soldiers": 60,
        "unlocks": None,
    },
    {
        "character": 'RC',
        "number": 15,
        "name": 'You will be bowled over!',
        "type": 'Smash challenge',
        "required_soldiers": 75,
        "unlocks": None,
    },
    {
        "character": 'RC',
        "number": 16,
        "name": 'Big air!',
        "type": 'Tag challenge',
        "required_soldiers": 80,
        "unlocks": None,
    },
    {
        "character": 'RC',
        "number": 17,
        "name": 'Sale!',
        "type": 'Collection challenge',
        "required_soldiers": 110,
        "unlocks": None,
    },
    {
        "character": 'RC',
        "number": 18,
        "name": 'Skid kid Sid!',
        "type": 'Lap trial challenge',
        "required_soldiers": 120,
        "unlocks": None,
    },
    {
        "character": 'RC',
        "number": 19,
        "name": 'Parking lot parting shot!',
        "type": 'Smash tag challenge',
        "required_soldiers": 130,
        "unlocks": 'Rocky Gibraltar',
    },
    {
        "character": 'RC',
        "number": 20,
        "name": 'Something in the attic!',
        "type": 'Survival race challenge',
        "required_soldiers": 135,
        "unlocks": None,
    },
    {
        "character": 'RC',
        "number": 21,
        "name": 'Countdown conundrum!',
        "type": 'Countdown race challenge',
        "required_soldiers": 148,
        "unlocks": None,
    },
    {
        "character": 'Bo Peep',
        "number": 1,
        "name": 'Sheep race cup',
        "type": 'Race tournament challenge',
        "required_soldiers": 0,
        "unlocks": None,
    },
    {
        "character": 'Bo Peep',
        "number": 2,
        "name": 'Flirting around the skirting',
        "type": 'Race challenge',
        "required_soldiers": 1,
        "unlocks": None,
    },
    {
        "character": 'Bo Peep',
        "number": 3,
        "name": 'Demolition car smash',
        "type": 'Smash tag challenge',
        "required_soldiers": 3,
        "unlocks": None,
    },
    {
        "character": 'Bo Peep',
        "number": 4,
        "name": 'Knockout neighbors',
        "type": 'Knockout race challenge',
        "required_soldiers": 9,
        "unlocks": None,
    },
    {
        "character": 'Bo Peep',
        "number": 5,
        "name": "Sid's sheep survival",
        "type": 'Survival race challenge',
        "required_soldiers": 10,
        "unlocks": None,
    },
    {
        "character": 'Bo Peep',
        "number": 6,
        "name": 'Bowling pin pickup',
        "type": 'Collection challenge',
        "required_soldiers": 15,
        "unlocks": None,
    },
    {
        "character": 'Bo Peep',
        "number": 7,
        "name": 'Bowling down the competition',
        "type": 'Smash challenge',
        "required_soldiers": 22,
        "unlocks": None,
    },
    {
        "character": 'Bo Peep',
        "number": 8,
        "name": 'Icicle race',
        "type": 'Lap trial challenge',
        "required_soldiers": 25,
        "unlocks": None,
    },
    {
        "character": 'Bo Peep',
        "number": 9,
        "name": 'Hanging around the neighborhood',
        "type": 'Endurance challenge',
        "required_soldiers": 27,
        "unlocks": None,
    },
    {
        "character": 'Bo Peep',
        "number": 10,
        "name": 'Off ground tag?',
        "type": 'Tag challenge',
        "required_soldiers": 30,
        "unlocks": None,
    },
    {
        "character": 'Bo Peep',
        "number": 11,
        "name": 'Put up your dukes',
        "type": 'Smash tournament challenge',
        "required_soldiers": 45,
        "unlocks": None,
    },
    {
        "character": 'Bo Peep',
        "number": 12,
        "name": 'Dinner is served',
        "type": 'Collection challenge',
        "required_soldiers": 50,
        "unlocks": None,
    },
    {
        "character": 'Bo Peep',
        "number": 13,
        "name": 'A battle to be served!',
        "type": 'Smash challenge',
        "required_soldiers": 60,
        "unlocks": None,
    },
    {
        "character": 'Bo Peep',
        "number": 14,
        "name": 'Skate date',
        "type": 'Survival race challenge (reverse)',
        "required_soldiers": 70,
        "unlocks": 'Slinky Dog',
    },
    {
        "character": 'Bo Peep',
        "number": 15,
        "name": 'Back to the trophy',
        "type": 'Race tournament challenge (reverse)',
        "required_soldiers": 80,
        "unlocks": None,
    },
    {
        "character": 'Bo Peep',
        "number": 16,
        "name": "Baby sitting at Sid's",
        "type": 'Super survival race challenge',
        "required_soldiers": 100,
        "unlocks": None,
    },
    {
        "character": 'Rex',
        "number": 1,
        "name": 'Tyrannosaurus trophy',
        "type": 'Race tournament challenge',
        "required_soldiers": 21,
        "unlocks": None,
    },
    {
        "character": 'Rex',
        "number": 2,
        "name": 'Reverse parking test Rex!',
        "type": 'Endurance challenge (reverse)',
        "required_soldiers": 21,
        "unlocks": None,
    },
    {
        "character": 'Rex',
        "number": 3,
        "name": 'Knockout offers at the mall',
        "type": 'Knockout race challenge (reverse)',
        "required_soldiers": 25,
        "unlocks": None,
    },
    {
        "character": 'Rex',
        "number": 4,
        "name": 'Game over Rex?',
        "type": 'Smash challenge',
        "required_soldiers": 27,
        "unlocks": None,
    },
    {
        "character": 'Rex',
        "number": 5,
        "name": 'Skate a saurus Rex!',
        "type": 'Race challenge (reverse)',
        "required_soldiers": 30,
        "unlocks": None,
    },
    {
        "character": 'Rex',
        "number": 6,
        "name": 'New territory for Rex!',
        "type": 'Race challenge',
        "required_soldiers": 30,
        "unlocks": None,
    },
    {
        "character": 'Rex',
        "number": 7,
        "name": 'Reverse a saurus Rex!',
        "type": 'Race tournament challenge (reverse)',
        "required_soldiers": 45,
        "unlocks": None,
    },
    {
        "character": 'Rex',
        "number": 8,
        "name": "Sid's yard clearance!",
        "type": 'Collection challenge',
        "required_soldiers": 45,
        "unlocks": None,
    },
    {
        "character": 'Rex',
        "number": 9,
        "name": 'Survive the move Rex!',
        "type": 'Survival race challenge',
        "required_soldiers": 55,
        "unlocks": None,
    },
    {
        "character": 'Rex',
        "number": 10,
        "name": 'Crazy attic rally',
        "type": 'Lap trial challenge',
        "required_soldiers": 65,
        "unlocks": None,
    },
    {
        "character": 'Rex',
        "number": 11,
        "name": 'Air and sea Rex cue!',
        "type": 'Lap trial challenge (reverse)',
        "required_soldiers": 65,
        "unlocks": None,
    },
    {
        "character": 'Rex',
        "number": 12,
        "name": 'Parking or darting?',
        "type": 'Target challenge',
        "required_soldiers": 80,
        "unlocks": None,
    },
    {
        "character": 'Rex',
        "number": 13,
        "name": 'Battlesaurus Rex',
        "type": 'Smash challenge',
        "required_soldiers": 80,
        "unlocks": None,
    },
    {
        "character": 'Rex',
        "number": 14,
        "name": 'Racersaurus Rex!',
        "type": 'Race challenge',
        "required_soldiers": 85,
        "unlocks": None,
    },
    {
        "character": 'Rex',
        "number": 15,
        "name": 'Avoid extinction Rex!',
        "type": 'Smash tournament challenge',
        "required_soldiers": 90,
        "unlocks": None,
    },
    {
        "character": 'Rex',
        "number": 16,
        "name": 'Keep up or you are out Rex!',
        "type": 'Knockout race challenge',
        "required_soldiers": 100,
        "unlocks": None,
    },
    {
        "character": 'Rex',
        "number": 17,
        "name": 'Parking sure is tricky round here Rex!',
        "type": 'Smash tag challenge',
        "required_soldiers": 105,
        "unlocks": None,
    },
    {
        "character": 'Rex',
        "number": 18,
        "name": 'Yard boy Rex?',
        "type": 'Race challenge',
        "required_soldiers": 110,
        "unlocks": None,
    },
    {
        "character": 'Rex',
        "number": 19,
        "name": 'Easy as 3 2 1 Rex',
        "type": 'Countdown race challenge',
        "required_soldiers": 110,
        "unlocks": None,
    },
    {
        "character": 'Rex',
        "number": 20,
        "name": 'Crazy pizza',
        "type": 'Super survival race challenge',
        "required_soldiers": 154,
        "unlocks": None,
    },
    {
        "character": 'Hamm',
        "number": 1,
        "name": 'Adventures in pork',
        "type": 'Race tournament challenge',
        "required_soldiers": 46,
        "unlocks": None,
    },
    {
        "character": 'Hamm',
        "number": 2,
        "name": 'Keeping up with the neighbors',
        "type": 'Knockout race challenge (reverse)',
        "required_soldiers": 50,
        "unlocks": None,
    },
    {
        "character": 'Hamm',
        "number": 3,
        "name": 'Parking ticket',
        "type": 'Endurance challenge',
        "required_soldiers": 52,
        "unlocks": None,
    },
    {
        "character": 'Hamm',
        "number": 4,
        "name": "Tiny pork's skateoff",
        "type": 'Race tournament challenge',
        "required_soldiers": 58,
        "unlocks": None,
    },
    {
        "character": 'Hamm',
        "number": 5,
        "name": 'Super fast pizza delivery',
        "type": 'Lap trial challenge (reverse)',
        "required_soldiers": 58,
        "unlocks": None,
    },
    {
        "character": 'Hamm',
        "number": 6,
        "name": 'Skating bacon!',
        "type": 'Smash challenge',
        "required_soldiers": 63,
        "unlocks": None,
    },
    {
        "character": 'Hamm',
        "number": 7,
        "name": 'Cash and carry',
        "type": 'Race tournament challenge',
        "required_soldiers": 65,
        "unlocks": None,
    },
    {
        "character": 'Hamm',
        "number": 8,
        "name": 'Ancient pork action',
        "type": 'Survival race challenge',
        "required_soldiers": 68,
        "unlocks": None,
    },
    {
        "character": 'Hamm',
        "number": 9,
        "name": 'Knockout parking Hamm',
        "type": 'Knockout race challenge',
        "required_soldiers": 68,
        "unlocks": None,
    },
    {
        "character": 'Hamm',
        "number": 10,
        "name": 'Moving money bank',
        "type": 'Endurance challenge',
        "required_soldiers": 80,
        "unlocks": None,
    },
    {
        "character": 'Hamm',
        "number": 11,
        "name": 'Neighborhood speed watch!',
        "type": 'Lap trial challenge (reverse)',
        "required_soldiers": 80,
        "unlocks": None,
    },
    {
        "character": 'Hamm',
        "number": 12,
        "name": 'A collection of parking tickets?',
        "type": 'Collection challenge',
        "required_soldiers": 92,
        "unlocks": None,
    },
    {
        "character": 'Hamm',
        "number": 13,
        "name": "Can you survive Sid's house Hamm?",
        "type": 'Super survival race challenge',
        "required_soldiers": 94,
        "unlocks": None,
    },
    {
        "character": 'Hamm',
        "number": 14,
        "name": 'What do points make?',
        "type": 'Race tournament challenge',
        "required_soldiers": 100,
        "unlocks": None,
    },
    {
        "character": 'Hamm',
        "number": 15,
        "name": 'Battling bacon',
        "type": 'Smash tournament challenge',
        "required_soldiers": 140,
        "unlocks": None,
    },
    {
        "character": 'Hamm',
        "number": 16,
        "name": 'Fastest pig in the west',
        "type": 'Race challenge',
        "required_soldiers": 140,
        "unlocks": None,
    },
    {
        "character": 'Hamm',
        "number": 17,
        "name": 'Sale survival',
        "type": 'Survival race challenge',
        "required_soldiers": 150,
        "unlocks": None,
    },
    {
        "character": 'Slinky',
        "number": 1,
        "name": 'Prolonged pizza!',
        "type": 'Super survival race challenge (reverse)',
        "required_soldiers": 71,
        "unlocks": None,
    },
    {
        "character": 'Slinky',
        "number": 2,
        "name": 'Springy trophy',
        "type": 'Race tournament challenge',
        "required_soldiers": 71,
        "unlocks": None,
    },
    {
        "character": 'Slinky',
        "number": 3,
        "name": 'Racing in a lofty place!',
        "type": 'Race challenge',
        "required_soldiers": 75,
        "unlocks": None,
    },
    {
        "character": 'Slinky',
        "number": 4,
        "name": 'Yard dog',
        "type": 'Lap trial challenge (reverse)',
        "required_soldiers": 80,
        "unlocks": None,
    },
    {
        "character": 'Slinky',
        "number": 5,
        "name": 'Snow good Slinky Dog',
        "type": 'Knockout race challenge (reverse)',
        "required_soldiers": 80,
        "unlocks": None,
    },
    {
        "character": 'Slinky',
        "number": 6,
        "name": 'Snow saver',
        "type": 'Collection challenge',
        "required_soldiers": 90,
        "unlocks": None,
    },
    {
        "character": 'Slinky',
        "number": 7,
        "name": "Sid's spring clean survivor!",
        "type": 'Survival race challenge',
        "required_soldiers": 90,
        "unlocks": None,
    },
    {
        "character": 'Slinky',
        "number": 8,
        "name": 'Speed skating Slinky Dog',
        "type": 'Endurance challenge',
        "required_soldiers": 91,
        "unlocks": None,
    },
    {
        "character": 'Slinky',
        "number": 9,
        "name": 'Fetch those skates',
        "type": 'Knockout race challenge',
        "required_soldiers": 120,
        "unlocks": None,
    },
    {
        "character": 'Slinky',
        "number": 10,
        "name": 'Hot dog trophy',
        "type": 'Race tournament challenge',
        "required_soldiers": 125,
        "unlocks": None,
    },
    {
        "character": 'Slinky',
        "number": 11,
        "name": 'No dog allowed',
        "type": 'Smash tag challenge',
        "required_soldiers": 129,
        "unlocks": None,
    },
    {
        "character": 'Slinky',
        "number": 12,
        "name": 'Dinner is in the dog',
        "type": 'Smash challenge',
        "required_soldiers": 130,
        "unlocks": None,
    },
    {
        "character": 'Slinky',
        "number": 13,
        "name": 'Chasing your tail?',
        "type": 'Race challenge (reverse)',
        "required_soldiers": 132,
        "unlocks": None,
    },
    {
        "character": 'Slinky',
        "number": 14,
        "name": 'Old sea dog',
        "type": 'Lap trial challenge',
        "required_soldiers": 140,
        "unlocks": None,
    },
    {
        "character": 'Slinky',
        "number": 15,
        "name": 'Seaside dog chase',
        "type": 'Tag challenge',
        "required_soldiers": 150,
        "unlocks": None,
    },
    {
        "character": 'Slinky',
        "number": 16,
        "name": 'A walk in the park?',
        "type": 'Target challenge',
        "required_soldiers": 168,
        "unlocks": None,
    },
    {
        "character": 'Slinky',
        "number": 17,
        "name": 'Dog gone',
        "type": 'Countdown race challenge',
        "required_soldiers": 169,
        "unlocks": None,
    },
    {
        "character": 'Slinky',
        "number": 18,
        "name": "Andy's speed off",
        "type": 'Survival race challenge',
        "required_soldiers": 170,
        "unlocks": None,
    },
    {
        "character": 'Slinky',
        "number": 19,
        "name": 'Top dog',
        "type": 'Knockout race tournament challenge',
        "required_soldiers": 170,
        "unlocks": None,
    },
    {
        "character": 'Slinky',
        "number": 20,
        "name": 'Neighborhood watchdog',
        "type": 'Race challenge (reverse)',
        "required_soldiers": 185,
        "unlocks": None,
    },
    {
        "character": 'Mr. Potato Head',
        "number": 1,
        "name": 'Potato cup',
        "type": 'Race tournament challenge',
        "required_soldiers": 95,
        "unlocks": None,
    },
    {
        "character": 'Mr. Potato Head',
        "number": 2,
        "name": "Don't become a baked potato!",
        "type": 'Smash tournament challenge',
        "required_soldiers": 95,
        "unlocks": None,
    },
    {
        "character": 'Mr. Potato Head',
        "number": 3,
        "name": 'Fry like the wind',
        "type": 'Lap trial challenge',
        "required_soldiers": 96,
        "unlocks": None,
    },
    {
        "character": 'Mr. Potato Head',
        "number": 4,
        "name": 'Knockout spud',
        "type": 'Knockout race challenge (reverse)',
        "required_soldiers": 110,
        "unlocks": None,
    },
    {
        "character": 'Mr. Potato Head',
        "number": 5,
        "name": 'Community spud',
        "type": 'Endurance challenge',
        "required_soldiers": 115,
        "unlocks": None,
    },
    {
        "character": 'Mr. Potato Head',
        "number": 6,
        "name": 'New house mash',
        "type": 'Super survival race challenge (reverse)',
        "required_soldiers": 118,
        "unlocks": None,
    },
    {
        "character": 'Mr. Potato Head',
        "number": 7,
        "name": "K.O.'d potato?",
        "type": 'Knockout race challenge',
        "required_soldiers": 125,
        "unlocks": None,
    },
    {
        "character": 'Mr. Potato Head',
        "number": 8,
        "name": 'Funny what you find in your attic!',
        "type": 'Collection challenge',
        "required_soldiers": 125,
        "unlocks": None,
    },
    {
        "character": 'Mr. Potato Head',
        "number": 9,
        "name": 'Seaside spud',
        "type": 'Endurance challenge (reverse)',
        "required_soldiers": 126,
        "unlocks": None,
    },
    {
        "character": 'Mr. Potato Head',
        "number": 10,
        "name": 'Seaside spud tag',
        "type": 'Smash tag challenge',
        "required_soldiers": 140,
        "unlocks": None,
    },
    {
        "character": 'Mr. Potato Head',
        "number": 11,
        "name": 'Pole position potato',
        "type": 'Race challenge',
        "required_soldiers": 140,
        "unlocks": None,
    },
    {
        "character": 'Mr. Potato Head',
        "number": 12,
        "name": "Nacho's for the film?",
        "type": 'Smash challenge',
        "required_soldiers": 144,
        "unlocks": None,
    },
    {
        "character": 'Mr. Potato Head',
        "number": 13,
        "name": 'K.O. snow potato',
        "type": 'Knockout race challenge',
        "required_soldiers": 146,
        "unlocks": None,
    },
    {
        "character": 'Mr. Potato Head',
        "number": 14,
        "name": 'Pizza and chips?',
        "type": 'Tag challenge',
        "required_soldiers": 150,
        "unlocks": None,
    },
    {
        "character": 'Mr. Potato Head',
        "number": 15,
        "name": 'Target skater',
        "type": 'Target challenge',
        "required_soldiers": 159,
        "unlocks": None,
    },
    {
        "character": 'Mr. Potato Head',
        "number": 16,
        "name": 'Spud meets scud?',
        "type": 'Race challenge (reverse)',
        "required_soldiers": 170,
        "unlocks": None,
    },
    {
        "character": 'Mr. Potato Head',
        "number": 17,
        "name": 'Fast hash brown',
        "type": 'Race tournament challenge',
        "required_soldiers": 170,
        "unlocks": None,
    },
    {
        "character": 'Mr. Potato Head',
        "number": 18,
        "name": "Spud they like? Don't think snow!",
        "type": 'Tag challenge',
        "required_soldiers": 175,
        "unlocks": 'Lenny',
    },
    {
        "character": 'Mr. Potato Head',
        "number": 19,
        "name": "Surviving Sid's smash",
        "type": 'Survival race challenge',
        "required_soldiers": 180,
        "unlocks": None,
    },
    {
        "character": 'LGM',
        "number": 1,
        "name": 'Little green trophy',
        "type": 'Race tournament challenge',
        "required_soldiers": 103,
        "unlocks": None,
    },
    {
        "character": 'LGM',
        "number": 2,
        "name": 'Claw through to victory',
        "type": 'Smash tournament challenge',
        "required_soldiers": 103,
        "unlocks": None,
    },
    {
        "character": 'LGM',
        "number": 3,
        "name": 'Hoarding the billboard',
        "type": 'Collection challenge',
        "required_soldiers": 105,
        "unlocks": None,
    },
    {
        "character": 'LGM',
        "number": 4,
        "name": 'The crazy parking lot',
        "type": 'Super survival race challenge',
        "required_soldiers": 110,
        "unlocks": None,
    },
    {
        "character": 'LGM',
        "number": 5,
        "name": 'A test of stamina',
        "type": 'Endurance challenge',
        "required_soldiers": 110,
        "unlocks": None,
    },
    {
        "character": 'LGM',
        "number": 6,
        "name": 'Food on the go',
        "type": 'Race challenge',
        "required_soldiers": 110,
        "unlocks": None,
    },
    {
        "character": 'LGM',
        "number": 7,
        "name": 'Pronto pizza delivery',
        "type": 'Lap trial challenge',
        "required_soldiers": 129,
        "unlocks": None,
    },
    {
        "character": 'LGM',
        "number": 8,
        "name": 'Water logged wild race',
        "type": 'Knockout race challenge',
        "required_soldiers": 133,
        "unlocks": None,
    },
    {
        "character": 'LGM',
        "number": 9,
        "name": 'Catch those bargain L.G.M.',
        "type": 'Smash tag challenge',
        "required_soldiers": 138,
        "unlocks": None,
    },
    {
        "character": 'LGM',
        "number": 10,
        "name": 'Holiday present run',
        "type": 'Collection challenge',
        "required_soldiers": 150,
        "unlocks": None,
    },
    {
        "character": 'LGM',
        "number": 11,
        "name": 'Snow joke',
        "type": 'Tag challenge',
        "required_soldiers": 155,
        "unlocks": None,
    },
    {
        "character": 'LGM',
        "number": 12,
        "name": 'A stranger from the outside',
        "type": 'Race tournament challenge',
        "required_soldiers": 160,
        "unlocks": None,
    },
    {
        "character": 'LGM',
        "number": 13,
        "name": 'Lots of crazy pizza',
        "type": 'Survival race challenge',
        "required_soldiers": 160,
        "unlocks": None,
    },
    {
        "character": 'Rocky',
        "number": 1,
        "name": 'Muscle cup',
        "type": 'Race tournament challenge',
        "required_soldiers": 131,
        "unlocks": None,
    },
    {
        "character": 'Rocky',
        "number": 2,
        "name": "Let's see who is the strongest",
        "type": 'Survival race challenge',
        "required_soldiers": 131,
        "unlocks": None,
    },
    {
        "character": 'Rocky',
        "number": 3,
        "name": "Andy's house monster mash!",
        "type": 'Super survival race challenge',
        "required_soldiers": 133,
        "unlocks": None,
    },
    {
        "character": 'Rocky',
        "number": 4,
        "name": "Rocky's rally challenge",
        "type": 'Race tournament challenge',
        "required_soldiers": 136,
        "unlocks": None,
    },
    {
        "character": 'Rocky',
        "number": 5,
        "name": 'Lights, camera, action!',
        "type": 'Smash challenge',
        "required_soldiers": 138,
        "unlocks": None,
    },
    {
        "character": 'Rocky',
        "number": 6,
        "name": 'Skate fast strongman!',
        "type": 'Lap trial challenge',
        "required_soldiers": 145,
        "unlocks": None,
    },
    {
        "character": 'Rocky',
        "number": 7,
        "name": 'Keep on running!',
        "type": 'Endurance challenge',
        "required_soldiers": 150,
        "unlocks": None,
    },
    {
        "character": 'Rocky',
        "number": 8,
        "name": 'A knockout shopping trip!',
        "type": 'Knockout race challenge',
        "required_soldiers": 150,
        "unlocks": None,
    },
    {
        "character": 'Rocky',
        "number": 9,
        "name": 'Fill her up Rocky!',
        "type": 'Collection challenge',
        "required_soldiers": 155,
        "unlocks": None,
    },
    {
        "character": 'Rocky',
        "number": 10,
        "name": 'It will be tough to win this Rocky!',
        "type": 'Smash tournament challenge',
        "required_soldiers": 159,
        "unlocks": None,
    },
    {
        "character": 'Rocky',
        "number": 11,
        "name": 'Flip the pizza Gibraltar',
        "type": 'Race challenge (reverse)',
        "required_soldiers": 160,
        "unlocks": None,
    },
    {
        "character": 'Rocky',
        "number": 12,
        "name": "Don't be a stick in the mud!",
        "type": 'Smash tag challenge',
        "required_soldiers": 168,
        "unlocks": None,
    },
    {
        "character": 'Rocky',
        "number": 13,
        "name": 'Skate on Rocky dude!',
        "type": 'Collection challenge',
        "required_soldiers": 169,
        "unlocks": None,
    },
    {
        "character": 'Rocky',
        "number": 14,
        "name": 'Party at the pier?',
        "type": 'Race challenge',
        "required_soldiers": 179,
        "unlocks": 'Babyface',
    },
    {
        "character": 'Rocky',
        "number": 15,
        "name": 'Strongman contest Rocky',
        "type": 'Knockout race tournament challenge',
        "required_soldiers": 181,
        "unlocks": None,
    },
    {
        "character": 'Rocky',
        "number": 16,
        "name": 'Eating contest!',
        "type": 'Survival race challenge',
        "required_soldiers": 185,
        "unlocks": None,
    },
    {
        "character": 'Lenny',
        "number": 1,
        "name": '10 pin target',
        "type": 'Target challenge',
        "required_soldiers": 176,
        "unlocks": None,
    },
    {
        "character": 'Lenny',
        "number": 2,
        "name": 'Wind up cup',
        "type": 'Race tournament challenge',
        "required_soldiers": 176,
        "unlocks": None,
    },
    {
        "character": 'Lenny',
        "number": 3,
        "name": 'Lenny one lens?',
        "type": 'Race tournament challenge',
        "required_soldiers": 180,
        "unlocks": None,
    },
    {
        "character": 'Lenny',
        "number": 4,
        "name": 'Yard hide and seek',
        "type": 'Knockout race challenge',
        "required_soldiers": 180,
        "unlocks": None,
    },
    {
        "character": 'Lenny',
        "number": 5,
        "name": 'Binocular battle',
        "type": 'Smash tournament challenge',
        "required_soldiers": 185,
        "unlocks": None,
    },
    {
        "character": 'Lenny',
        "number": 6,
        "name": 'They come from out of space',
        "type": 'Knockout race challenge',
        "required_soldiers": 187,
        "unlocks": None,
    },
    {
        "character": 'Lenny',
        "number": 7,
        "name": 'Bo-peeping tom?',
        "type": 'Race challenge',
        "required_soldiers": 190,
        "unlocks": None,
    },
    {
        "character": 'Lenny',
        "number": 8,
        "name": 'Short survival',
        "type": 'Survival race challenge',
        "required_soldiers": 195,
        "unlocks": None,
    },
    {
        "character": 'Babyface',
        "number": 1,
        "name": 'Surviving at home',
        "type": 'Super survival race challenge (reverse)',
        "required_soldiers": 180,
        "unlocks": None,
    },
    {
        "character": 'Babyface',
        "number": 2,
        "name": 'Target dolly!',
        "type": 'Target challenge',
        "required_soldiers": 180,
        "unlocks": None,
    },
    {
        "character": 'Babyface',
        "number": 3,
        "name": "Sid's toy trophy",
        "type": 'Countdown race challenge (reverse)',
        "required_soldiers": 180,
        "unlocks": None,
    },
    {
        "character": 'Babyface',
        "number": 4,
        "name": 'Put a brave face on',
        "type": 'Smash tournament challenge',
        "required_soldiers": 180,
        "unlocks": None,
    },
    {
        "character": 'Babyface',
        "number": 5,
        "name": 'Babyface, one more lap?',
        "type": 'Race tournament challenge',
        "required_soldiers": 180,
        "unlocks": None,
    },
    {
        "character": 'Babyface',
        "number": 6,
        "name": 'Babyface survivor race',
        "type": 'Survival race challenge',
        "required_soldiers": 185,
        "unlocks": None,
    },
    {
        "character": 'Babyface',
        "number": 7,
        "name": 'Pier? Oh dear!',
        "type": 'Super survival race challenge',
        "required_soldiers": 195,
        "unlocks": None,
    },
    {
        "character": 'Babyface',
        "number": 8,
        "name": 'House warming',
        "type": 'Knockout race challenge',
        "required_soldiers": 195,
        "unlocks": None,
    },
]

CHALLENGES_BY_CHARACTER = {}
for challenge in CHALLENGES:
    CHALLENGES_BY_CHARACTER.setdefault(challenge["character"], []).append(challenge)

CHALLENGE_LOOKUP = {
    (challenge["character"], challenge["number"]): challenge
    for challenge in CHALLENGES
}

CHALLENGE_TYPES = sorted({challenge["type"] for challenge in CHALLENGES if challenge["type"] is not None})
